activation: sine
adaround: true
adaround_iterations: 1000
adaround_reg: 0.0001
batch_size: 1
bitwidth: 8
code: arithmetic
data_root: data
dataset: test_celeba
downscaling_factor: 1
encoding: nerf
encoding_scale: 1.4
epochs: 50
epochs_til_ckpt: 5000
exp_glob: '*'
exp_root: exp/val_basic_celeba
ff_dims: 12
hidden_dims: 24
hidden_layers: 3
inner_lr: 1.0e-05
l1_reg: 1.0e-05
lr: 0.0005
lr_type: per_parameter_per_step
maml_adaptation_steps: 3
maml_batch_size: 1
maml_dataset: CelebA
maml_epochs: 1
outer_lr: 5.0e-05
patience: 500
retrain: true
retrain_epochs: 300
retrain_lr: 1.0e-06
skip_existing: true
steps_til_summary: 1000
warmup: 100
